package com.sperasoft.sie.tools.interest;

import java.util.Date;
import java.util.List;

/**
 * Created by Ilya K on 7/16/2017.
 */
public class SummaryReportDescription {
    /*
      PUT reports/summary/description/[name]
      Parameters:
         + {name} - *name* in URL and in payload xml should match

      Body:
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<summaryReportDescription>
    <name>npmt-events-Summary-Report-Description</name>
    <uiPages>
        <uiPage>npmt-events</uiPage>
    </uiPages>
    <title>npmt-events Summary Report Description Test API</title>
    <releaseName>Release API Test</releaseName>
    <metadata>
        <line>Q1</line>
        <environment>All</environment>
        <version>NP15.7</version>
        <branch>release/major</branch>
    </metadata>
    <startTime>2015-09-13T21:00:00.000Z</startTime>
</summaryReportDescription>

      Notes:
        + if name is not specified in body it is automatically generated by INTEREST
        + releaseName - name of corresponding Release
     */

    private static final String API_ENDPOINT = "/interest/api/reports/summary/description/[name]";

    private String name;
    private List<String> uiPages;
    private String title;
    private String releaseName;
    private class metadata {
        String line;
        String environment;
        String version;
        String branch;
    }
    private Date startTime;

}
