package com.sperasoft.sie.tools.interest;

import java.util.Date;

/**
 * Created by Ilya K on 7/16/2017.
 */
public class UiPageCreator {
      /*
      POST collector/ui-page
      Parameters:
        + None

      Body:
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<uiPage>
  <name>npmt-events</name>
  <xAxis>Line</xAxis>
  <yAxis>testScriptName</yAxis>
  <viewName>npmt-events</viewName>
  <releaseName>Release API Test</releaseName>
  <startTime>2015-02-26T21:00:00.000Z</startTime>
  <title>npmt-events uiPage Test API</title>
</uiPage>

      Notes:
        + if name is not specified in body it is automatically generated by INTEREST
        + releaseName - name of corresponding Release
        + viewName - name of corresponding View on collector
     */

    private static final String API_ENDPOINT = "/interest/api/collector/ui-page";

    private String name;
    private String xAxis = "Line";
    private String yAxis = "testScriptName";
    private String viewName;
    private String releaseName;
    private Date startTime;
    private String title;
}
