package com.sperasoft.sie.tools.interest;

import com.sperasoft.sie.tools.interest.converters.UiPageXmlConverter;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;

import java.time.ZonedDateTime;

/**
 * Created by Ilya K on 7/16/2017.
 */
public class UiPage {
      /*
      POST collector/ui-page
      Parameters:
        + None

      Body:
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<uiPage>
  <name>npmt-events</name>
  <xAxis>Line</xAxis>
  <yAxis>testScriptName</yAxis>
  <viewName>npmt-events</viewName>
  <releaseName>Release API Test</releaseName>
  <startTime>2015-02-26T21:00:00.000Z</startTime>
  <title>npmt-events uiPage Test API</title>
</uiPage>

      Notes:
        + if name is not specified in body it is automatically generated by INTEREST
        + releaseName - name of corresponding Release
        + viewName - name of corresponding View on collector
     */

    private String interestBaseUrl;
    private static final String API_ENDPOINT = "/interest/api/collector/ui-page";

    private String name;
    private String xAxis = "Line";
    private String yAxis = "testScriptName";
    private String viewName;
    private String releaseName;
    private ZonedDateTime startTime;
    private String title;

    public UiPage(String interestBaseUrl) {
        this.interestBaseUrl = interestBaseUrl;
    }

    public String getApiUrl() {
        return this.interestBaseUrl + UiPage.API_ENDPOINT;
    }

    public String toXml() {
        XStream xStream = new XStream(new DomDriver());
        xStream.registerConverter(new UiPageXmlConverter());
        xStream.alias("uiPage", UiPage.class);
        return xStream.toXML(this);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getxAxis() {
        return xAxis;
    }

    public void setxAxis(String xAxis) {
        this.xAxis = xAxis;
    }

    public String getyAxis() {
        return yAxis;
    }

    public void setyAxis(String yAxis) {
        this.yAxis = yAxis;
    }

    public String getViewName() {
        return viewName;
    }

    public void setViewName(String viewName) {
        this.viewName = viewName;
    }

    public String getReleaseName() {
        return releaseName;
    }

    public void setReleaseName(String releaseName) {
        this.releaseName = releaseName;
    }

    public ZonedDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(ZonedDateTime startTime) {
        this.startTime = startTime;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }


}
