package com.sperasoft.sie.tools.interest;

import com.sperasoft.sie.tools.interest.converters.ViewXmlConverter;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.DomDriver;

import java.util.Collection;
import java.util.Map;

/**
 * Created by Ilya K on 7/16/2017.
 */
public class View {
    /*
      POST /collector/gui/view
      Parameters:
        + None

      Body:
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<viewElement>
  <name>npmt-events</name>
  <parameters>
    <parameter>
      <name>Line</name>
      <value>q1</value>
    </parameter>
    <parameter>
      <name>testSuiteName</name>
      <value>bi-tests/npmt-events</value>
    </parameter>
  </parameters>
</viewElement>

      Notes:
        + if name is not specified in body it is automatically generated by INTEREST
     */

    private String interestBaseUrl;
    private static final String API_ENDPOINT = "/interest/api/collector/gui/view";

    private String name;
    private Collection<Map<String, String>> parameters;

    public View(String interestBaseUrl) {
        this.interestBaseUrl = interestBaseUrl;
    }


    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Collection<Map<String, String>> getParameters() {
        return parameters;
    }

    public void setParameters(Collection<Map<String, String>> parameters) {
        this.parameters = parameters;
    }

    public String toXml() {
        XStream xStream = new XStream(new DomDriver());
        xStream.registerConverter(new ViewXmlConverter());
        xStream.alias("viewElement", View.class);
        return xStream.toXML(this);
    }

    public String getApiUrl() {
        return this.interestBaseUrl + View.API_ENDPOINT;
    }
}
